server:
  port: 1580
spring:
  profiles:
    active: dev
  application:
    name: project-gt
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: postgres
    password: 123456
    hikari:
      min-idle: 10
      max-pool-size: 100
      connection-timeout: 300000
      max-lifetime: 1800000
      is-auto-commit: true
      connection-test-query: select 1
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件最大大小 默认1M
      max-request-size: 20MB  # 总文件最大大小 默认10M
# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.gt.**.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true #驼峰下划线转换
      logic-delete-value: 1 #逻辑删除
      logic-not-delete-value: 0 #逻辑未删除
      id-type: ASSIGN_ID
    banner: false